export enum Rawline {
  Thin = 'Rawline-Thin',
  ThinItalic = 'Rawline-ThinItalic',
  ExtraLight = 'Rawline-ExtraLight',
  ExtraLightItalic = 'Rawline-ExtraLightItalic',
  Light = 'Rawline-Light',
  LightItalic = 'Rawline-LightItalic',
  Regular = 'Rawline-Regular',
  RegularItalic = 'Rawline-RegularItalic',
  Medium = 'Rawline-Medium',
  MediumItalic = 'Rawline-MediumItalic',
  Semibold = 'Rawline-SemiBold',
  SemiboldItalic = 'Rawline-SemiBoldItalic',
  Bold = 'Rawline-Bold',
  BoldItalic = 'Rawline-BoldItalic',
  Extrabold = 'Rawline-ExtraBold',
  ExtraboldItalic = 'Rawline-ExtraBoldItalic',
  Black = 'Rawline-Black',
  BlackItalic = 'Rawline-BlackItalic',
}
